package com.astraf.hrgpslogger

enum class GpsDecisionReason {
    ACCEPTED_GOOD_ACCURACY,
    ACCEPTED_DEGRADED_LOW_TRUST,
    REJECTED_BAD_ACCURACY,
    REJECTED_IMPLAUSIBLE_SPEED,
    REJECTED_INVALID_TIMESTAMP,
    REJECTED_TOO_FREQUENT,
    REJECTED_MISSING_ACCURACY,
    IGNORED_TEMPORARY_NOISE,
    BRIDGED_SHORT_GAP,
    NEW_SEGMENT_LONG_GAP,
    NEW_SEGMENT_IMPLAUSIBLE_GAP,
    NEW_SEGMENT_EXTERNAL_PAUSE,
    WAITING_FOR_FIRST_FIX,
}
